--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: test_planetary_planner; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE test_planetary_planner WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE test_planetary_planner OWNER TO postgres;

\connect test_planetary_planner

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."User" (id, username) VALUES (22, 'testing0');
INSERT INTO public."User" (id, username) VALUES (25, 'testing1');
INSERT INTO public."User" (id, username) VALUES (27, 'testing2');
INSERT INTO public."User" (id, username) VALUES (28, 'testing3');


--
-- Data for Name: Location; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Location" (id, user_id, city, region, timezone, latitude, longitude) VALUES (28, 22, 'Berlin', 'Europe', 'Europe/Berlin', 52.520008, 13.404954);


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (23, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (24, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (25, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (26, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (27, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (28, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);
INSERT INTO public."Events" (id, user_id, location_id, description, busy, planet, start_time, end_time, hour) VALUES (29, 22, 28, NULL, true, 'Venus', '2022-02-22 04:52:14.992857', '2022-02-22 06:00:28.524533', 22);


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.alembic_version (version_num) VALUES ('8c74e7258582');


--
-- Name: Events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Events_id_seq"', 29, true);


--
-- Name: Location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Location_id_seq"', 28, true);


--
-- Name: User_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_id_seq"', 28, true);


--
-- PostgreSQL database dump complete
--

