"""start/end time in Events

Revision ID: 3824dd847b8f
Revises: 2454f4a29f04
Create Date: 2022-06-23 05:47:19.015823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3824dd847b8f'
down_revision = '2454f4a29f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Events', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_constraint('Events_time_key', 'Events', type_='unique')
    op.drop_column('Events', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('Events_time_key', 'Events', ['time'])
    op.drop_column('Events', 'end_time')
    op.drop_column('Events', 'start_time')
    # ### end Alembic commands ###
