"""planet col in events

Revision ID: 800ac47686c8
Revises: ece27cda8a8e
Create Date: 2022-06-21 08:17:26.354003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800ac47686c8'
down_revision = 'ece27cda8a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('planet', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('Events', 'planet')
    # ### end Alembic commands ###
