"""manually added hours to events table, now making that col un nullable

Revision ID: 8c74e7258582
Revises: d1944f242c25
Create Date: 2022-06-23 09:12:03.634505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c74e7258582'
down_revision = 'd1944f242c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Events', 'hour',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Events', 'hour',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
