"""hour column in Events

Revision ID: d1944f242c25
Revises: 3824dd847b8f
Create Date: 2022-06-23 09:09:03.539780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1944f242c25'
down_revision = '3824dd847b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'hour')
    # ### end Alembic commands ###
